name: Lint

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  pull_request:
  push:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-node@v4.0.2
      - run: npm install
      - run: npm run test-fix
      - name: "Auto Commit"
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
            commit_message: 'style fixes by eslint'
