name: Lint

on:
  pull_request:
  push:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
      - run: npm install
      - run: npm ci # or yarn install
      - run: mocha --reporter dot
      - uses: sibiraj-s/action-eslint@v3.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # optional
          eslint-args: '--ignore-path=.gitignore --quiet --fix'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
      - name: "Auto Commit"
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
            commit_message: 'style fixes by eslint'
